
const data=window.LITTERATUDE_CATALOG,state={visited:JSON.parse(localStorage.getItem("ltVisited")||"[]")},q=id=>document.getElementById(id);q("version").textContent="— "+data.meta.version;
function finishIntro(){q("intro").classList.add("done")}q("skipIntro").onclick=finishIntro;setTimeout(finishIntro,4800);
function hs(item,id,future=false){const b=document.createElement("button");b.className="hotspot";b.id="hotspot-"+id;Object.assign(b.style,{left:item.hotspot.left+"%",top:item.hotspot.top+"%",width:item.hotspot.width+"%",height:item.hotspot.height+"%"});b.innerHTML=`<span>${item.title}${future?" — à venir":""}</span>`;b.onclick=()=>future?show(`<h2>Quartier ${item.title}</h2><p>Ce quartier figure déjà sur la carte afin de rappeler que la Cité restera toujours inachevée.</p>`):openDistrict(id);q("hotspots").appendChild(b)}data.districts.forEach(d=>hs(d,d.id));data.futureDistricts.forEach((d,i)=>hs(d,"f"+i,true));
function openDistrict(id){document.querySelectorAll(".hotspot").forEach(h=>h.classList.remove("active"));q("hotspot-"+id).classList.add("active");const d=data.districts.find(x=>x.id===id);q("districtType").textContent=d.type;q("districtTitle").textContent=d.title;q("districtDescription").textContent=d.description;q("districtPortrait").src=d.portrait;q("rail").innerHTML="";d.rooms.forEach(r=>{const c=document.createElement("article");c.className="card";c.innerHTML=`<img src="${r.cover}"><div><h3>${r.title}</h3><p>${r.text}</p></div>`;c.onclick=()=>openRoom(r,id);q("rail").appendChild(c)});q("drawer").classList.add("open");q("hint").style.opacity=0}
function closeDrawer(){q("drawer").classList.remove("open");document.querySelectorAll(".hotspot").forEach(h=>h.classList.remove("active"));q("hint").style.opacity=1}
function openRoom(r,id){const k=id+":"+r.title;if(!state.visited.includes(k)){state.visited.push(k);localStorage.setItem("ltVisited",JSON.stringify(state.visited))}if(r.type==="video")show(`<h2>${r.title}</h2><video controls poster="${r.cover}"><source src="${r.media}" type="video/mp4"></video><p>${r.text}</p>`);else if(r.type==="youtube")show(`<h2>${r.title}</h2><iframe src="${r.media}" allowfullscreen></iframe><p>${r.text}</p>`);else if(r.type==="missing-video")show(`<h2>${r.title}</h2><img src="${r.cover}"><p>${r.text}</p><p><strong>Le clip du Voyageur doit encore être compressé sous 100 Mo avant sa publication sur GitHub.</strong></p>`);else if(r.type==="future")show(`<h2>${r.title}</h2><p>${r.text}</p><p><strong>Cette porte est déjà réservée.</strong></p>`);else show(`<h2>${r.title}</h2><img src="${r.cover}"><p>${r.text}</p>`)}
function show(h){q("modalContent").innerHTML=h;q("modal").classList.add("open")}function closeModal(){q("modal").classList.remove("open");q("modalContent").innerHTML=""}
q("closeDrawer").onclick=closeDrawer;q("overviewBtn").onclick=closeDrawer;q("leftArrow").onclick=()=>q("rail").scrollBy({left:-520,behavior:"smooth"});q("rightArrow").onclick=()=>q("rail").scrollBy({left:520,behavior:"smooth"});q("modalClose").onclick=closeModal;q("modal").onclick=e=>{if(e.target===q("modal"))closeModal()};
q("lamp").onclick=()=>show(`<h2>La Lampe du Village</h2><p>Le savoir est accueilli librement. La transmission est offerte. Chaque contribution permet que la lumière reste allumée pour le prochain promeneur.</p>`);
q("emblemsBtn").onclick=()=>show(`<h2>Les emblèmes</h2><div class="emblems">${data.emblems.map(e=>`<div class="emblem">${e[0]}<b>${e[1]}</b><small>${e[2]}</small></div>`).join("")}</div>`);
q("passportBtn").onclick=()=>show(`<h2>Passeport du Promeneur</h2><div class="passport"><strong>${state.visited.length} porte(s) visitée(s)</strong><p>Le Passeport raconte un chemin personnel.</p></div>`);
